require('plugins')
require('settings')
require('keymappings')
require('config/lsp')
require('config/tree-sitter')
require('xresources')
require('config/compe')
require('config/comment')
require('config/pears')
-- require('config/indent-blankline')
require('config/barbar')
require('config/galaxyline')
require('config/toggleterm')
require('config/nvim-tree')
require('gitsigns').setup()
require('colorizer').setup()
