#! bin/bash

alias nvimconfig='nvim $HOME/.config/nvim/init.lua'
alias polybarconfig='nvim /home/xirius/.config/polybar/config'
alias porfi='sudo'
alias reboot='systemctl reboot'
alias sail='bash vendor/bin/sail'
alias shutdown='systemctl poweroff'
alias vim='nvim'
alias zshconfig='nvim /home/xirius/.zshrc'
alias dev='cd ~/Development'
alias run='npm run'
alias config='cd ~/.config'
