#! /bin/sh

exec /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#7AA2F7"
bspc config normal_border_color "#4e5173"
bspc config presel_feedback_color "#7AA2F7"
bspc config pointer_motion_interval 16
bspc config top_padding 24

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "Android Emulator" state=floating

wmname LG3D &
xset +fp $HOME/.local/share/fonts &
xset fp rehash &
feh --bg-fill $HOME/Imágenes/zelda.jpg &
compton &
dunst &
polybar -r example &
redshift -O 4000 &
xautolock -time 10 -locker "i3lock -c 000000 && sleep 10 && xset s activate" &
unclutter &
